# Generated by Django 3.2.12 on 2022-07-14 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_user_last_active_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 14, 12, 13, 18, 770156), verbose_name='Last Active Date'),
        ),
    ]
