# Generated by Django 3.2.12 on 2022-07-14 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_user_last_active_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 14, 14, 5, 31, 932998), verbose_name='Last Active Date'),
        ),
    ]
