# Generated by Django 3.2.12 on 2022-07-20 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Costumer Name')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('cell', models.CharField(blank=True, max_length=255, verbose_name='Cell')),
                ('cell_2', models.CharField(blank=True, max_length=255, verbose_name='Cell 2')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Telephone')),
                ('fax', models.CharField(blank=True, max_length=255, verbose_name='Fax')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.CharField(blank=True, max_length=255, verbose_name='Web Site')),
                ('logo', models.ImageField(blank=True, max_length=255, upload_to='', verbose_name='Logo')),
                ('logo_square', models.ImageField(blank=True, max_length=255, upload_to='', verbose_name='Logo Square')),
                ('active_status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, verbose_name='Status')),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
                'ordering': ('name',),
            },
        ),
    ]
